### ISSUE TITLE
Tweet/Media item not fully readable

### ISSUE THREAD

**Issue by lyndseysc** [FACxBeamery/Tom_Thomas_7_through_9#17]
You can't read the full text of the tweet and it is not clickable to expand or open at the moment (I presume this is something you are in progress on though!)

**Comment by thomas-galligan** [comment]
The idea is we show a (possibly) truncated version of the tweet/article, and provide a link for the user to see the whole text if they so wish. This means we can keep all the cards the same dimensions. Since code review, we've added a link to each tweet/article so they can be viewed in full on the host site.
